---
apiVersion: v1
kind: Service
metadata:
  name: showks-test
  namespace: showks
  labels:
    app: showks-test
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: app-port
  selector:
    app: showks-test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showks-test
  namespace: showks
  labels:
    app: showks-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showks-test
  template:
    metadata:
      labels:
        app: showks-test
    spec:
      containers:
        - name: showks-test
          image: containerdaysjp/showks-portal:stg-105423cc57994e9c652e6169066a8add1017fc4d
          ports:
            - name: app-port
              containerPort: 3000
              protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: showks-test
  namespace: showks
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: test.stg.showks.containerdays.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: showks-test
          servicePort: 3000

