---
apiVersion: v1
kind: Service
metadata:
  name: showks-test-temp
  namespace: showks
  labels:
    app: showks-test-temp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: app-port
  selector:
    app: showks-test-temp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showks-test-temp
  namespace: showks
  labels:
    app: showks-test-temp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showks-test-temp
  template:
    metadata:
      labels:
        app: showks-test-temp
    spec:
      containers:
        - name: showks-test-temp
          image: nginx
          ports:
            - name: app-port
              containerPort: 80
              protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: showks-test-temp
  namespace: showks
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"
spec:
  rules:
  - host: test.stg.showks.containerdays.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: showks-test-temp
          servicePort: 80
  - host: test.prod.showks.containerdays.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: showks-test-temp
          servicePort: 80
